POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "francesca", 
    "password": "passwordFrancesca"
}

###
GET http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "francesca", 
    "password": "passwordFrancesca"
}

### test for test federico-create post

POST http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZnJhbmNlc2NhIiwiaWF0IjoxNzM0ODA0NTA1fQ.ru11KykmwGwHWdzxv68ByZ7iMnyj_PGuzFxyEiJbde8
Content-Type: application/json

{
    "title":"test for francesca's post",
    "caption":"",
    "body":"second test"
}

### test for franco-create post

POST http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZnJhbmNvIiwiaWF0IjoxNzM0NzkzODY1fQ.Z_pKubb5qdc2wwbKQ-ASDxzmAcYGNnjc3swOa3fDf48
Content-Type: application/json

{
    "title":"test with token",
    "caption":"",
    "body":"second test"
}

### get post info and related comments
GET http://localhost:3000/posts

### create comment
POST http://localhost:3000/comments/5
Content-Type: application/json

{
    "userId":"6",
    "text":"test first comment creation"
}